server:
  port: 9005
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: bluntapp22@gmail.com
    password: Blunt@123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

